apiVersion: v1
kind: Pod
metadata:
  name: sample-hostnetwork
spec:
  hostNetwork: true
  containers:
    - name: hello-world
      image: hello-world
      ports:
        - containerPort: 8080
      env:
        - name: "NGINX_PORT"
          value: "8080"