apiVersion: v1
kind: Pod
metadata:
  name: sample-hostnetwork
spec:
  hostNetwork: true
  containers:
    - name: nginx-container
      image: nginx:1.16
      ports:
        - containerPort: 8080
      env:
        - name: "NGINX_PORT"
          value: "8080"